export const DEBUGGER_LOADED = "DEBUGGER LOADED";
export const DEBUGGER_RECEIVED_EVENT = "DEBUGGER RECEIVED EVENT";
export const DEBUGGER_INIT = "DEBUGGER INIT";
export const DEBUGGER_PAUSE = "DEBUGGER PAUSE";
export const DEBUGGER_RESUME = "DEBUGGER RESUME";
export const DEBUGGER_INIT_ERROR = "DEBUGGER INIT ERROR";
export const DEBUGGER_SEARCH = "DEBUGGER SEARCH";
export const DEBUGGER_EVENT_SELECTED = "DEBUGGER EVENT SELECTED";
