export const DEBUGGER_LOADED = "DEBUGGER LOADED";
export const DEBUGGER_RECEIVED_EVENT = "DEBUGGER RECEIVED EVENT";
export const DEBUGGER_INIT = "DEBUGGER INIT";
export const DEBUGGER_PAUSED = "DEBUGGER PAUSED";
export const DEBUGGER_RESUMED = "DEBUGGER RESUMED";
export const DEBUGGER_INIT_ERROR = "DEBUGGER INIT ERROR";
